"""
RT-DOS Intelligence Platform
Module      : Market Regime Engine
Version     : 1.0.0
Status      : Production
Architecture: Intelligence Layer
"""

from typing import Dict, List


class MarketRegimeEngine:
    """
    Classifies the prevailing market regime for each asset.

    Version 1 uses the existing intelligence generated by the
    Technical, Momentum, ATR, Volume and Relative Strength engines.

    Future versions will incorporate:
        - India VIX
        - Market Breadth
        - Sector Rotation
        - Institutional Confidence Index
    """

    # ==========================================================
    # Public
    # ==========================================================

    def analyze(
        self,
        composite_data: List[Dict],
    ) -> List[Dict]:

        if not composite_data:
            return []

        output = []

        for asset in composite_data:

            score = asset.get("score", 0)

            regime = self._classify(score)

            asset = asset.copy()

            asset["market_regime"] = regime["regime"]
            asset["regime_confidence"] = regime["confidence"]
            asset["recommended_strategy"] = regime["strategy"]

            output.append(asset)

        return output

    # ==========================================================
    # Private
    # ==========================================================

    def _classify(
        self,
        score: float,
    ) -> Dict:

        if score >= 90:

            return {
                "regime": "Strong Bull Trend",
                "confidence": 95,
                "strategy": "Buy Strength",
            }

        if score >= 80:

            return {
                "regime": "Bull Trend",
                "confidence": 88,
                "strategy": "Buy Pullbacks",
            }

        if score >= 70:

            return {
                "regime": "Accumulation",
                "confidence": 80,
                "strategy": "Accumulate",
            }

        if score >= 60:

            return {
                "regime": "Breakout Watch",
                "confidence": 72,
                "strategy": "Watch Breakouts",
            }

        if score >= 50:

            return {
                "regime": "Sideways",
                "confidence": 65,
                "strategy": "Wait",
            }

        if score >= 40:

            return {
                "regime": "Distribution",
                "confidence": 70,
                "strategy": "Reduce Longs",
            }

        if score >= 30:

            return {
                "regime": "Bear Trend",
                "confidence": 82,
                "strategy": "Sell Rallies",
            }

        return {
            "regime": "High Risk",
            "confidence": 90,
            "strategy": "Capital Preservation",
        }
