"""
RT-DOS Intelligence Platform
Module      : Probability Engine
Version     : 1.0.0
Status      : Production
Architecture: Intelligence Layer
"""

from typing import Dict, List


class ProbabilityEngine:
    """
    Calculates trade probability and expected behaviour
    from the intelligence already generated by RT-DOS.

    Version 1
    ----------
    Uses:
        • Composite Score
        • Market Regime
        • Institutional Confidence

    Future Versions
    ---------------
        • ATR
        • India VIX
        • Sector Rotation
        • Market Breadth
        • Historical Win Rate
    """

    # ==========================================================
    # Public
    # ==========================================================

    def analyze(
        self,
        intelligence: List[Dict],
    ) -> List[Dict]:

        if not intelligence:
            return []

        output = []

        for asset in intelligence:

            probability = self._probability(asset)

            asset = asset.copy()

            asset["probability"] = probability
            asset["expected_move"] = self._expected_move(probability)
            asset["holding_period"] = self._holding_period(probability)
            asset["risk_reward"] = self._risk_reward(probability)

            output.append(asset)

        return output

    # ==========================================================
    # Private
    # ==========================================================

    def _probability(
        self,
        asset: Dict,
    ) -> int:

        score = asset.get("score", 0)

        confidence = asset.get(
            "institutional_confidence",
            score,
        )

        probability = int((score * 0.40) + (confidence * 0.60))

        return max(
            0,
            min(
                100,
                probability,
            ),
        )

    # ----------------------------------------------------------

    def _expected_move(
        self,
        probability: int,
    ) -> str:

        if probability >= 90:
            return "8–10%"

        if probability >= 80:
            return "6–8%"

        if probability >= 70:
            return "4–6%"

        if probability >= 60:
            return "3–5%"

        return "<3%"

    # ----------------------------------------------------------

    def _holding_period(
        self,
        probability: int,
    ) -> str:

        if probability >= 85:
            return "1–2 Days"

        if probability >= 70:
            return "2–4 Days"

        if probability >= 55:
            return "3–7 Days"

        return "Monitor"

    # ----------------------------------------------------------

    def _risk_reward(
        self,
        probability: int,
    ) -> str:

        if probability >= 85:
            return "1 : 4"

        if probability >= 70:
            return "1 : 3"

        if probability >= 55:
            return "1 : 2"

        return "Below 1 : 2"
