"""
RT-DOS Intelligence Platform
Module      : Executive Intelligence Panel
Version     : 2.0.0
Status      : Production
Architecture: Market Command Centre V2
"""

import streamlit as st


class SummaryPanel:

    def show(self, presentation):

        top = presentation.get("top_opportunity")

        if top is None:

            st.warning("No market intelligence available.")

            return

        # =====================================================
        # Executive Header
        # =====================================================

        st.subheader("🧠 Executive Intelligence")

        st.caption(
            "Institutional-style market summary generated from the RT-DOS Intelligence Pipeline."
        )

        # =====================================================
        # Executive Metrics
        # =====================================================

        c1, c2, c3 = st.columns(3)

        with c1:

            st.metric(
                "Best Opportunity",
                top["symbol"],
            )

            st.metric(
                "Decision",
                top["decision"],
            )

        with c2:

            st.metric(
                "Composite Score",
                top["score"],
            )

            st.metric(
                "Confidence",
                f'{top["confidence"]}%',
            )

        with c3:

            st.metric(
                "Grade",
                top["grade"],
            )

            st.metric(
                "Risk",
                top["risk"],
            )

        st.divider()

        # =====================================================
        # Executive Commentary
        # =====================================================

        commentary = self._build_commentary(
            presentation,
            top,
        )

        st.info(commentary)

        st.divider()

        # =====================================================
        # Trading Guidance
        # =====================================================

        st.success(
            self._trading_guidance(
                top,
                presentation,
            )
        )

    # =========================================================

    def _build_commentary(
        self,
        presentation,
        top,
    ):

        return f"""
### Executive Market Assessment

• **Market Status:** {presentation['market_status']}

• **Market Health:** {presentation['market_health']}%

• **Assets Analysed:** {presentation['total_assets']}

• **Leading Opportunity:** {top['symbol']}

• **Current Decision:** {top['decision']}

• **Overall Confidence:** {top['confidence']}%

RT-DOS currently identifies **{top['symbol']}** as the strongest opportunity based on the combined intelligence generated by the Technical, Momentum, ATR, Volume and Relative Strength engines.
"""

    # =========================================================

    def _trading_guidance(
        self,
        top,
        presentation,
    ):

        decision = top["decision"]

        if decision == "STRONG BUY":

            action = (
                "Market conditions are supportive. "
                "Focus on high-quality long opportunities while maintaining disciplined position sizing."
            )

        elif decision == "BUY":

            action = "Constructive conditions. New positions may be considered after confirming price action."

        elif decision == "WATCH":

            action = "Remain patient. Monitor developing opportunities and wait for stronger confirmation."

        elif decision == "HOLD":

            action = "Avoid initiating fresh trades until market conditions improve."

        else:

            action = "Risk appears elevated. Capital preservation should take priority."

        return f"""
### RT-DOS Trading Guidance

**Current Market Status:** {presentation['market_status']}

**Recommended Action:** {action}
"""
